### ISSUE TITLE
ValueError: Input contains NaN, infinity or a value too large for dtype('float64')

### ISSUE THREAD

**Issue by hchintalapudi** [klarman-cell-observatory/demuxEM#12]
Hi,
I'm trying to use demuxEM for my hashing data and get this error:

```
(demux) chintalh@nl003:~ % demuxEM -p 8 --generate-diagnostic-plots /gstore/data/genomics/congee_rest_runs/6123a9cf17c8a42bb21f8b20/SAM24396521/output/single_cell_citeseq/b1a4fc07-7ed2-41f8-80a7-7355d63369ff/call-run_cellranger_count/execution/SAM24396521/outs/raw_feature_bc_matrix.h5 CiteSeq/hto_count_matrix_SAM24396521.csv CiteSeq/demuxEM_SAM24396521_output
2021-09-27 13:23:45,030 - pegasusio.readwrite - INFO - 10x file '/gstore/data/genomics/congee_rest_runs/6123a9cf17c8a42bb21f8b20/SAM24396521/output/single_cell_citeseq/b1a4fc07-7ed2-41f8-80a7-7355d63369ff/call-run_cellranger_count/execution/SAM24396521/outs/raw_feature_bc_matrix.h5' is loaded.
2021-09-27 13:23:45,030 - pegasusio.readwrite - INFO - Function 'read_input' finished in 3.82s.
2021-09-27 13:23:45,075 - pegasusio.readwrite - INFO - csv file 'CiteSeq/hto_count_matrix_SAM24396521.csv' is loaded.
2021-09-27 13:23:45,075 - pegasusio.readwrite - INFO - Function 'read_input' finished in 0.03s.
/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/demuxEM/tools/demuxEM.py:39: RuntimeWarning: divide by zero encountered in log10
  counts_log10 = np.log10(hashing_data.obs["counts"].values.reshape(-1, 1))
Traceback (most recent call last):
  File "/gstore/home/chintalh/miniconda3/envs/demux/bin/demuxEM", line 8, in <module>
    sys.exit(main())
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/demuxEM/__main__.py", line 9, in main
    command.execute()
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/demuxEM/commands/DemuxEM.py", line 65, in execute
    **kwargs
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/demuxEM/pipeline/pipeline.py", line 37, in run_pipeline
    estimate_background_probs(hashing_data, random_state=kwargs["random_state"])
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/demuxEM/tools/demuxEM.py", line 40, in estimate_background_probs
    kmeans = KMeans(n_clusters=2, random_state=random_state).fit(counts_log10)
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/sklearn/cluster/_kmeans.py", line 1145, in fit
    accept_large_sparse=False,
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/sklearn/base.py", line 557, in _validate_data
    X = check_array(X, **check_params)
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/sklearn/utils/validation.py", line 792, in check_array
    _assert_all_finite(array, allow_nan=force_all_finite == "allow-nan")
  File "/gstore/home/chintalh/miniconda3/envs/demux/lib/python3.7/site-packages/sklearn/utils/validation.py", line 116, in _assert_all_finite
    type_err, msg_dtype if msg_dtype is not None else X.dtype
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').
```

my input_hto_csv_file:
```
> hto_count_matrix_SAM24396521[,1:3]
                             AAACCTGAGCATCATC-1 AAACCTGAGCCACGCT-1 AAACCTGCAAGCGCTC-1
Total-seqC-1-SAM24396521                      0                  2                  0
Total-seqC-2-SAM24396521                      4                  7                  1
Total-seqC-3-SAM24396521                     98                 12                 10
WT1.1-SAM24396521                             3                  0                  0
Negative-control-SAM24396521                  0                  0                  0
```

I don't see anything wrong with my inputs,Any tips on how to solve this? thanks!

**Comment by bli25** [comment]
Hi @hchintalapudi , the error is due to cell barcodes with 0 hashtag counts. We have fixed this bug on the master branch and will include this fix in the next release.
